const IMAGE_GENERATE_ENDPOINT =
  (typeof SUPABASE_URL !== "undefined" && SUPABASE_URL)
    ? `${SUPABASE_URL}/functions/v1/image-generate`
    : "";

const FREE_LIMIT = 3;
const HISTORY_KEY = "gw_image_history";

function byId(id) {
  return document.getElementById(id);
}

function setStatus(message, isError = false) {
  const el = byId("generationStatus");
  if (!el) return;
  el.textContent = message;
  el.style.color = isError ? "#D9503F" : "";
}

function escapeHTML(value) {
  const div = document.createElement("div");
  div.textContent = String(value ?? "");
  return div.innerHTML;
}

function saveHistory(item) {
  try {
    const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
    history.unshift(item);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 20)));
  } catch (_) {}
}

function updateUsage(remaining) {
  const count = byId("usageCount");
  const bar = byId("usageBar");

  if (typeof remaining !== "number") return;

  const safeRemaining = Math.max(0, remaining);
  if (count) count.textContent = `${safeRemaining}/${FREE_LIMIT}`;
  if (bar) {
    bar.style.width = `${Math.min(100, (safeRemaining / FREE_LIMIT) * 100)}%`;
  }
}

function showLoading() {
  const preview = byId("preview");
  if (!preview) return;

  preview.innerHTML = `
    <div>
      <div class="loading-ring"></div>
      <strong>Creating your image...</strong>
      <p>GrandWave is securely routing your request through the image generation service.</p>
    </div>
  `;
}

function showError(message) {
  const preview = byId("preview");
  if (!preview) return;

  preview.innerHTML = `
    <div>
      <strong>Generation couldn't be completed</strong>
      <p>${escapeHTML(message)}</p>
    </div>
  `;
}

function showResult(imageUrl, provider) {
  const preview = byId("preview");
  if (!preview) return;

  const safeProvider = escapeHTML(provider || "GrandWave AI");

  preview.innerHTML = `
    <div style="width:100%">
      <img class="preview-image" src="${escapeHTML(imageUrl)}" alt="Generated image">
      <div style="margin-top:12px;color:var(--text-dim);font-size:.72rem">
        Generated by ${safeProvider}
      </div>
      <div class="preview-toolbar">
        <a class="preview-link" href="${escapeHTML(imageUrl)}" download="grandwave-image.png">Download image</a>
        <a class="preview-link alt" href="${escapeHTML(imageUrl)}" target="_blank" rel="noopener">Open full image</a>
      </div>
    </div>
  `;
}

async function getAccessToken() {
  if (typeof sb === "undefined" || !sb?.auth) {
    throw new Error("GrandWave authentication is not available on this page.");
  }

  const { data, error } = await sb.auth.getSession();

  if (error) throw new Error(error.message || "Unable to read your session.");

  const token = data?.session?.access_token;
  if (!token) {
    throw new Error("Your session has expired. Please sign in again.");
  }

  return token;
}

async function generateImage() {
  const prompt = byId("prompt")?.value.trim();
  const style = byId("style")?.value || "Photorealistic";
  const aspectRatio = byId("aspectRatio")?.value || "1:1 Square";
  const quality = byId("quality")?.value || "Standard";
  const button = byId("generateBtn");
  const surprise = byId("surpriseBtn");

  if (!prompt) {
    setStatus("Enter an image description first.", true);
    byId("prompt")?.focus();
    return;
  }

  if (!IMAGE_GENERATE_ENDPOINT) {
    showError("The Supabase generation endpoint is not configured.");
    setStatus("Generation endpoint unavailable.", true);
    return;
  }

  if (button) {
    button.disabled = true;
    button.textContent = "Generating...";
  }
  if (surprise) surprise.disabled = true;

  setStatus("Secure generation started...");
  showLoading();

  try {
    const token = await getAccessToken();

    const response = await fetch(IMAGE_GENERATE_ENDPOINT, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
        apikey: typeof SUPABASE_ANON_KEY !== "undefined" ? SUPABASE_ANON_KEY : ""
      },
      body: JSON.stringify({
        action: "generate",
        prompt,
        tool: "text-to-image",
        style,
        aspectRatio,
        quality,
        provider: "auto"
      })
    });

    let data = {};
    try {
      data = await response.json();
    } catch (_) {
      data = {};
    }

    if (!response.ok) {
      if (response.status === 429 && data.code === "DAILY_LIMIT") {
        updateUsage(Number(data.remaining ?? 0));
        throw new Error("Daily generation limit reached. You can continue after your daily allowance resets.");
      }
      throw new Error(data.error || `Generation failed (${response.status}).`);
    }

    if (!data.imageUrl) {
      throw new Error("The image service returned no image.");
    }

    showResult(data.imageUrl, data.provider);
    updateUsage(Number(data.remaining ?? 0));
    setStatus(
      `Image created successfully${data.provider ? ` with ${data.provider}` : ""}.`
    );

    saveHistory({
      imageUrl: data.imageUrl,
      prompt,
      style,
      aspectRatio,
      quality,
      provider: data.provider || "auto",
      createdAt: new Date().toISOString()
    });
  } catch (error) {
    console.error("GrandWave image generation:", error);
    showError(error?.message || "Image generation failed.");
    setStatus(error?.message || "Image generation failed.", true);
  } finally {
    if (button) {
      button.disabled = false;
      button.textContent = "Generate image";
    }
    if (surprise) surprise.disabled = false;
  }
}

function surpriseMe() {
  const prompts = [
    "A futuristic African city at golden hour, cinematic photography, realistic architecture, atmospheric light, premium editorial composition",
    "A cinematic mountain landscape above the clouds at sunrise, photorealistic, dramatic natural light, ultra detailed",
    "A premium modern workspace at night, realistic photography, glass surfaces, subtle neon reflections, cinematic lighting",
    "A mysterious coastal village after rain, photorealistic, moody sky, wet streets, soft cinematic reflections",
    "A futuristic train moving through a vast African landscape at sunset, cinematic realism, detailed environment, atmospheric perspective"
  ];

  const prompt = byId("prompt");
  if (prompt) {
    prompt.value = prompts[Math.floor(Math.random() * prompts.length)];
    prompt.focus();
  }
}

async function syncUsageFromLocalFallback() {
  // The server is authoritative. This only prevents the UI from looking empty
  // before the first successful generation response.
  const count = byId("usageCount");
  const bar = byId("usageBar");
  if (!count || !bar) return;

  count.textContent = "3/3";
  bar.style.width = "100%";
}

window.addEventListener("load", syncUsageFromLocalFallback);
window.generateImage = generateImage;
window.surpriseMe = surpriseMe;